apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order-svc
  template:
    metadata:
    spec:
      containers:
      - name: order-svc
        image: order-svc:local 
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        envFrom:
        - configMapRef:
            name: order-svc-env
        - secretRef:
            name: order-svc-secrets
        volumeMounts:
        - name: config-volume
          mountPath: /opt/order_svc/config/
          readOnly: true
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "1Gi"
      volumes:
      - name: config-volume
        configMap:
          name: order-svc-config