apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: order-svc

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
- name: order-svc-config
  files:
    - config.yaml
- name: order-svc-env
  literals:
    - APP_HOME=$(APP_HOME_SVC)
    - CFG_PATH=$(CFG_PATH)
    - PORT=$(GRPC_PORT)
    - KAFKA_BROKER=$(KAFKA_BROKER)
    - LOKI_ENDPOINT=$(LOKI_ENDPOINT)
    - TEMPO_ENDPOINT=$(TEMPO_ENDPOINT)
    - PROMETHEUS_ENDPOINT=$(PROMETHEUS_ENDPOINT)

secretGenerator:
- name: order-svc-secrets
  literals:
    - DB_DSN=$(DB_DSN)