apiVersion: v1
kind: Service
metadata:
  name: order-svc-service
  namespace: order-system
  labels:
    part-of: order-system
spec:
  selector:
    app: order-svc
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 8082
      targetPort: 8082
  type: ClusterIP