apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app.kubernetes.io/name: order-svc
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 8082
      targetPort: 8082
  type: ClusterIP