global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'order_api'
    static_configs:
      - targets: ['order_api:8081']
  - job_name: 'order_svc'
    static_configs:
      - targets: ['order_svc:8082']