// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/adapters/api/orderpb/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order Status enum
type OrderStatus int32

const (
	OrderStatus_STATUS_PENDING   OrderStatus = 0
	OrderStatus_STATUS_CONFIRMED OrderStatus = 1
	OrderStatus_STATUS_FAILED    OrderStatus = 2
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "STATUS_PENDING",
		1: "STATUS_CONFIRMED",
		2: "STATUS_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"STATUS_PENDING":   0,
		"STATUS_CONFIRMED": 1,
		"STATUS_FAILED":    2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_adapters_api_orderpb_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_internal_adapters_api_orderpb_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_adapters_api_orderpb_order_proto_rawDescGZIP(), []int{0}
}

// Order message
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         map[string]int32       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_internal_adapters_api_orderpb_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_api_orderpb_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_internal_adapters_api_orderpb_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_STATUS_PENDING
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request by ID
type GetOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRequest) Reset() {
	*x = GetOrderByIDRequest{}
	mi := &file_internal_adapters_api_orderpb_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRequest) ProtoMessage() {}

func (x *GetOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_api_orderpb_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_api_orderpb_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request by status
type GetOrdersByStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OrderStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByStatusRequest) Reset() {
	*x = GetOrdersByStatusRequest{}
	mi := &file_internal_adapters_api_orderpb_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByStatusRequest) ProtoMessage() {}

func (x *GetOrdersByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_api_orderpb_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_api_orderpb_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrdersByStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_STATUS_PENDING
}

var File_internal_adapters_api_orderpb_order_proto protoreflect.FileDescriptor

const file_internal_adapters_api_orderpb_order_proto_rawDesc = "" +
	"\n" +
	")internal/adapters/api/orderpb/order.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.order.Order.ItemsEntryR\x05items\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.order.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"%\n" +
	"\x13GetOrderByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x18GetOrdersByStatusRequest\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.order.OrderStatusR\x06status*J\n" +
	"\vOrderStatus\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x00\x12\x14\n" +
	"\x10STATUS_CONFIRMED\x10\x01\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x022\x8e\x01\n" +
	"\fOrderService\x128\n" +
	"\fGetOrderByID\x12\x1a.order.GetOrderByIDRequest\x1a\f.order.Order\x12D\n" +
	"\x11GetOrdersByStatus\x12\x1f.order.GetOrdersByStatusRequest\x1a\f.order.Order0\x01BKZIgithub.com/Anacardo89/order_svc_hex/internal/adapters/api/orderpb;orderpbb\x06proto3"

var (
	file_internal_adapters_api_orderpb_order_proto_rawDescOnce sync.Once
	file_internal_adapters_api_orderpb_order_proto_rawDescData []byte
)

func file_internal_adapters_api_orderpb_order_proto_rawDescGZIP() []byte {
	file_internal_adapters_api_orderpb_order_proto_rawDescOnce.Do(func() {
		file_internal_adapters_api_orderpb_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_api_orderpb_order_proto_rawDesc), len(file_internal_adapters_api_orderpb_order_proto_rawDesc)))
	})
	return file_internal_adapters_api_orderpb_order_proto_rawDescData
}

var file_internal_adapters_api_orderpb_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_adapters_api_orderpb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_adapters_api_orderpb_order_proto_goTypes = []any{
	(OrderStatus)(0),                 // 0: order.OrderStatus
	(*Order)(nil),                    // 1: order.Order
	(*GetOrderByIDRequest)(nil),      // 2: order.GetOrderByIDRequest
	(*GetOrdersByStatusRequest)(nil), // 3: order.GetOrdersByStatusRequest
	nil,                              // 4: order.Order.ItemsEntry
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_internal_adapters_api_orderpb_order_proto_depIdxs = []int32{
	4, // 0: order.Order.items:type_name -> order.Order.ItemsEntry
	0, // 1: order.Order.status:type_name -> order.OrderStatus
	5, // 2: order.Order.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: order.Order.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: order.GetOrdersByStatusRequest.status:type_name -> order.OrderStatus
	2, // 5: order.OrderService.GetOrderByID:input_type -> order.GetOrderByIDRequest
	3, // 6: order.OrderService.GetOrdersByStatus:input_type -> order.GetOrdersByStatusRequest
	1, // 7: order.OrderService.GetOrderByID:output_type -> order.Order
	1, // 8: order.OrderService.GetOrdersByStatus:output_type -> order.Order
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_adapters_api_orderpb_order_proto_init() }
func file_internal_adapters_api_orderpb_order_proto_init() {
	if File_internal_adapters_api_orderpb_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_api_orderpb_order_proto_rawDesc), len(file_internal_adapters_api_orderpb_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_api_orderpb_order_proto_goTypes,
		DependencyIndexes: file_internal_adapters_api_orderpb_order_proto_depIdxs,
		EnumInfos:         file_internal_adapters_api_orderpb_order_proto_enumTypes,
		MessageInfos:      file_internal_adapters_api_orderpb_order_proto_msgTypes,
	}.Build()
	File_internal_adapters_api_orderpb_order_proto = out.File
	file_internal_adapters_api_orderpb_order_proto_goTypes = nil
	file_internal_adapters_api_orderpb_order_proto_depIdxs = nil
}
