apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: postgres-credentials
  literals:
    - postgres-root-password=$(DB_PASSWORD) 
    - postgres-password=$(DB_PASSWORD)
generatorOptions:
  disableNameSuffixHash: true