apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order-api
  template:
    metadata:
    spec:
      containers:
      - name: order-api
        image: order-api:local 
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: order-api-env
        # - secretRef: 
        #     name: order-api-secrets
        volumeMounts:
        - name: config-volume
          mountPath: /opt/order_api/config/
          readOnly: true
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "1Gi"
      volumes:
      - name: config-volume
        configMap:
          name: order-api-config